### ISSUE TITLE
Cannot access empty property (MSSQL Table)

### ISSUE THREAD

**Issue by ammo8600** [apioo/fusio#182]
Getting error on using action to fetch from MSSQL table.

**Cannot access empty property in /home/fusio/www/fusio/vendor/psx/data/src/Visitor/StdClassSerializeVisitor.php on line 39**

{
    "success": false,
    "title": "Error",
    "message": "Cannot access empty property in \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/Visitor\/StdClassSerializeVisitor.php on line 39",
    "trace": "#0 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/Visitor\/SerializeVisitorAbstract.php(104): PSX\\Data\\Visitor\\StdClassSerializeVisitor->addObjectValue('', 'cheapddev', Object(stdClass))\n#1 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/GraphTraverser.php(75): PSX\\Data\\Visitor\\SerializeVisitorAbstract->visitObjectValueEnd()\n#2 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/GraphTraverser.php(109): PSX\\Data\\GraphTraverser->traverseObject(Array, Object(PSX\\Data\\Visitor\\StdClassSerializeVisitor))\n#3 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/GraphTraverser.php(94): PSX\\Data\\GraphTraverser->traverseValue(Array, Object(PSX\\Data\\Visitor\\StdClassSerializeVisitor))\n#4 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/GraphTraverser.php(111): PSX\\Data\\GraphTraverser->traverseArray(Array, Object(PSX\\Data\\Visitor\\StdClassSerializeVisitor))\n#5 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/GraphTraverser.php(73): PSX\\Data\\GraphTraverser->traverseValue(Array, Object(PSX\\Data\\Visitor\\StdClassSerializeVisitor))\n#6 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/GraphTraverser.php(109): PSX\\Data\\GraphTraverser->traverseObject(Array, Object(PSX\\Data\\Visitor\\StdClassSerializeVisitor))\n#7 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/GraphTraverser.php(45): PSX\\Data\\GraphTraverser->traverseValue(Array, Object(PSX\\Data\\Visitor\\StdClassSerializeVisitor))\n#8 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/Writer\/Json.php(44): PSX\\Data\\GraphTraverser->traverse(Array, Object(PSX\\Data\\Visitor\\StdClassSerializeVisitor))\n#9 \/home\/fusio\/www\/fusio\/vendor\/psx\/data\/src\/Processor.php(155): PSX\\Data\\Writer\\Json->write(Array)\n#10 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Http\/ResponseWriter.php(170): PSX\\Data\\Processor->write(Object(PSX\\Data\\Payload))\n#11 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Http\/ResponseWriter.php(127): PSX\\Framework\\Http\\ResponseWriter->setResponse(Object(PSX\\Http\\Response), Array, Object(PSX\\Framework\\Http\\WriterOptions))\n#12 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Controller\/SchemaApiAbstract.php(322): PSX\\Framework\\Http\\ResponseWriter->setBody(Object(PSX\\Http\\Response), Object(PSX\\Http\\Environment\\HttpResponse), Object(PSX\\Http\\Request))\n#13 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Controller\/SchemaApiAbstract.php(124): PSX\\Framework\\Controller\\SchemaApiAbstract->sendResponse(Object(PSX\\Api\\Resource\\Get), Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Environment\\HttpResponse))\n#14 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Controller\/ControllerAbstract.php(164): PSX\\Framework\\Controller\\SchemaApiAbstract->onGet(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#15 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Controller\/SchemaApiAbstract.php(98): PSX\\Framework\\Controller\\ControllerAbstract->onRequest(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#16 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Controller\/ControllerAbstract.php(138): PSX\\Framework\\Controller\\SchemaApiAbstract->onRequest(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#17 \/home\/fusio\/www\/fusio\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): PSX\\Framework\\Controller\\ControllerAbstract->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#18 \/home\/fusio\/www\/fusio\/vendor\/fusio\/impl\/src\/Filter\/Logger.php(87): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#19 \/home\/fusio\/www\/fusio\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Filter\\Logger->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#20 \/home\/fusio\/www\/fusio\/vendor\/fusio\/impl\/src\/Filter\/RequestLimit.php(82): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#21 \/home\/fusio\/www\/fusio\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Filter\\RequestLimit->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#22 \/home\/fusio\/www\/fusio\/vendor\/fusio\/impl\/src\/Filter\/Authentication.php(137): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#23 \/home\/fusio\/www\/fusio\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Filter\\Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#24 \/home\/fusio\/www\/fusio\/vendor\/fusio\/impl\/src\/Filter\/AssertMethod.php(95): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#25 \/home\/fusio\/www\/fusio\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Filter\\AssertMethod->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#26 \/home\/fusio\/www\/fusio\/vendor\/psx\/http\/src\/Filter\/UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#27 \/home\/fusio\/www\/fusio\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#28 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Loader\/Loader.php(123): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#29 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Loader\/Loader.php(102): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#30 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(125): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Loader\\Context))\n#31 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Environment\/WebServer\/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#32 \/home\/fusio\/www\/fusio\/vendor\/psx\/framework\/src\/Environment\/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#33 \/home\/fusio\/www\/fusio\/public\/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#34 {main}",
    "context": "35      }\n36  \n37      protected function addObjectValue($key, $value, &amp;$object)\n38      {\n<b>39          $object-&gt;$key = $value;\n<\/b>40      }\n41  \n42      protected function newArray()\n43      {\n"
}

**Comment by chriskapp** [comment]
Hi, could you show me the action code which data you set as response. I would guess that your action produces an array with an empty key which does not work with Fusio.

**Comment by ammo8600** [comment]
I am using the SQL-Table option as the action. and the response is set to Passthrough.

**Comment by chriskapp** [comment]
Ok, mhh could you show me the structure/data of the table. Also did the error occured if you simply request the endpoint through GET or do you actually POST data to the endpoint.
