### ISSUE TITLE
Missing quote to end the value in fusio install

### ISSUE THREAD

**Issue by SaudAlghamdi** [apioo/fusio#224]
Hello, 

When I'm try to run this command inside fusio project folder I face this issue : 

Command: `php bin/fusio install`

```
PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\FormatException: Missing quote to end the value in "/var/www/html/fusio/.env" at line 7.
...RECAPTCHA_SECRET=""\n...
                       ^ line 7 offset 408 in /var/www/html/fusio/vendor/symfony/dotenv/Dotenv.php:408
Stack trace:
#0 /var/www/html/fusio/vendor/symfony/dotenv/Dotenv.php(220): Symfony\Component\Dotenv\Dotenv->createFormatException('Missing quote t...')
#1 /var/www/html/fusio/vendor/symfony/dotenv/Dotenv.php(128): Symfony\Component\Dotenv\Dotenv->lexValue()
#2 /var/www/html/fusio/vendor/symfony/dotenv/Dotenv.php(56): Symfony\Component\Dotenv\Dotenv->parse('# Fusio\nFUSIO_P...', '/var/www/html/f...')
#3 /var/www/html/fusio/configuration.php(5): Symfony\Component\Dotenv\Dotenv->load('/var/www/html/f...')
#4 /var/www/html/fusio/vendor/psx/framework/src/Config/Config.php(72): include('/var/www/html/f...')
#5 /var/www/html/fusio/vendor/psx/framework/src/Dependency/Framework.php(53): PSX\Framework\Config\Config::fromFile('/var/www/html/f...')
#6 /var/www/h in /var/www/html/fusio/vendor/symfony/dotenv/Dotenv.php on line 408
```

**Comment by chriskapp** [comment]
Hi, mhh this sounds like a problem with the `.env` file. Which version of the `dotenv` library have you installed? You can check this with `composer info`

**Comment by chriskapp** [comment]
It looks like this issue is solved therefor I will close the issue. The latest release also includes a newer version of dotenv.
