### ISSUE TITLE
Call to a member function format() on null in /var/www/html/fusio/vendor/fusio/adapter-sql/src/Action/SqlTable.php on line 349

### ISSUE THREAD

**Issue by yusdirman** [apioo/fusio#239]
Hi I got error message when using SqlTable

Error Message: 
```
Call to a member function format() on null in /var/www/html/fusio/vendor/fusio/adapter-sql/src/Action/SqlTable.php on line 349
```

TrackTrace
```
#0 /var/www/html/fusio/vendor/fusio/adapter-sql/src/Action/SqlTable.php(190): Fusio\Adapter\Sql\Action\SqlTable->convertRow(Array, Object(Doctrine\DBAL\Connection), Object(Doctrine\DBAL\Schema\Table))
#1 /var/www/html/fusio/vendor/fusio/adapter-sql/src/Action/SqlTable.php(73): Fusio\Adapter\Sql\Action\SqlTable->doGetCollection(Object(Fusio\Engine\Request), Object(Doctrine\DBAL\Connection), Object(Doctrine\DBAL\Schema\Table), NULL, NULL, 20)
#2 /var/www/html/fusio/vendor/fusio/engine/src/Processor.php(70): Fusio\Adapter\Sql\Action\SqlTable->handle(Object(Fusio\Engine\Request), Object(Fusio\Engine\Parameters), Object(Fusio\Engine\Context))
#3 /var/www/html/fusio/vendor/fusio/impl/src/Service/Action/Executor.php(103): Fusio\Engine\Processor->execute(7, Object(Fusio\Engine\Request), Object(Fusio\Engine\Context))
#4 /var/www/html/fusio/vendor/fusio/impl/src/Backend/Api/Action/Execute.php(75): Fusio\Impl\Service\Action\Executor->execute(7, 'GET', Array, Array, Array, Object(PSX\Record\Record))
#5 /var/www/html/fusio/vendor/psx/framework/src/Controller/SchemaApiAbstract.php(137): Fusio\Impl\Backend\Api\Action\Execute->doPost(Object(PSX\Record\Record), Object(PSX\Http\Environment\HttpContext))
#6 /var/www/html/fusio/vendor/psx/framework/src/Controller/ControllerAbstract.php(172): PSX\Framework\Controller\SchemaApiAbstract->onPost(Object(PSX\Http\Request), Object(PSX\Http\Response))
#7 /var/www/html/fusio/vendor/psx/framework/src/Controller/SchemaApiAbstract.php(99): PSX\Framework\Controller\ControllerAbstract->onRequest(Object(PSX\Http\Request), Object(PSX\Http\Response))
#8 /var/www/html/fusio/vendor/psx/framework/src/Controller/ControllerAbstract.php(138): PSX\Framework\Controller\SchemaApiAbstract->onRequest(Object(PSX\Http\Request), Object(PSX\Http\Response))
#9 /var/www/html/fusio/vendor/psx/http/src/Filter/FilterChain.php(110): PSX\Framework\Controller\ControllerAbstract->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Http\Filter\FilterChain))
#10 /var/www/html/fusio/vendor/fusio/impl/src/Filter/Authentication.php(119): PSX\Http\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#11 /var/www/html/fusio/vendor/psx/http/src/Filter/FilterChain.php(110): Fusio\Impl\Filter\Authentication->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Http\Filter\FilterChain))
#12 /var/www/html/fusio/vendor/psx/http/src/Filter/UserAgentEnforcer.php(43): PSX\Http\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#13 /var/www/html/fusio/vendor/psx/http/src/Filter/FilterChain.php(110): PSX\Http\Filter\UserAgentEnforcer->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Http\Filter\FilterChain))
#14 /var/www/html/fusio/vendor/psx/framework/src/Loader/Loader.php(123): PSX\Http\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#15 /var/www/html/fusio/vendor/psx/framework/src/Loader/Loader.php(102): PSX\Framework\Loader\Loader->execute(Array, Object(PSX\Http\Request), Object(PSX\Http\Response))
#16 /var/www/html/fusio/vendor/psx/framework/src/Dispatch/Dispatch.php(125): PSX\Framework\Loader\Loader->load(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(Fusio\Impl\Loader\Context))
#17 /var/www/html/fusio/vendor/psx/framework/src/Environment/WebServer/Engine.php(47): PSX\Framework\Dispatch\Dispatch->route(Object(PSX\Http\Request), Object(PSX\Http\Response))
#18 /var/www/html/fusio/vendor/psx/framework/src/Environment/Environment.php(67): PSX\Framework\Environment\WebServer\Engine->serve(Object(PSX\Framework\Dispatch\Dispatch), Object(PSX\Framework\Config\Config))
#19 /var/www/html/fusio/public/index.php(29): PSX\Framework\Environment\Environment->serve()
#20 {main}
```

## Notes

It seems like the database table column is in DateTime format but the data is null.

looking at the codes in `SqlTable.php` line 349

```php
protected function convertRow(array $row, Connection $connection, Table $table)
    {
        $result = [];
        foreach ($row as $key => $value) {
            $type = $table->getColumn($key)->getType();
            $val  = $type->convertToPHPValue($value, $connection->getDatabasePlatform());

            if ($type instanceof Types\DateTimeType) {
                // below is line 349 in source code
                $val = $val->format(\DateTime::RFC3339);
            } elseif ($type instanceof Types\DateTimeTzType) {
                $val = $val->format(\DateTime::RFC3339_EXTENDED);
            } elseif ($type instanceof Types\TimeType) {
                $val = $val->format('H:i:s');
            } elseif ($type instanceof Types\BinaryType || $type instanceof Types\BlobType) {
                $val = base64_encode(stream_get_contents($val));
            } else {
                $val
            }

            $result[$key] = $val;
        }

        return $result;
    }
```

since the column type is in DateTime format, the coding will convert the data which is null to datetime format thus trigger the error 

## Suggestion

```
if (!is_null($val)){
                if ($type instanceof Types\DateTimeType) {
                    $val = $val->format(\DateTime::RFC3339);
                } elseif ($type instanceof Types\DateTimeTzType) {
                    $val = $val->format(\DateTime::RFC3339_EXTENDED);
                } elseif ($type instanceof Types\TimeType) {
                    $val = $val->format('H:i:s');
                } elseif ($type instanceof Types\BinaryType || $type instanceof Types\BlobType) {
                    $val = base64_encode(stream_get_contents($val));
                }
            }
```
## Results

the error eliminated but perhaps this method would raise other issues.. 

thank you

**Comment by chriskapp** [comment]
Hi, thanks for the report, yes it is indeed an issue. I have just commited a fix: 
https://github.com/apioo/fusio-adapter-sql/commit/4ea1375bbace5f58ccf1e0024e0234e2f9fba1a0
You can try the fix by updating the composer package `fusio/adapter-sql` to the latest version.

**Comment by chriskapp** [comment]
I will close this issue since there is nothing more to do here
