### ISSUE TITLE
Authorization is not working for endpoints in testing

### ISSUE THREAD

**Issue by jothikannan** [apioo/fusio#290]
I am writing test cases for my private endpoints which requires authentication, Authorization is working well when I try with Swagger-UI or Documentation, I can get the result with token  I have generated using `authorization/token` with Oauth2 using postman client. But when I try the same with test cases I am getting error like below

```
"success": false,
    "title": "PSX\\Http\\Exception\\UnauthorizedException",
    "message": "Signature verification failed in G:\\xampp\\htdocs\\fusio\\vendor\\fusio\\impl\\src\\Service\\Security\\TokenValidator.php on line 108",
    "trace": "#0 G:\\xampp\\htdocs\\fusio\\vendor\\fusio\\impl\\src\\Filter\\Authentication.php(62): Fusio\\Impl\\Service\\Security\\TokenValidator->assertAuthorization('GET', 'Bearer eyJ0eXAi...', Object(Fusio\\Impl\\Loader\\Context))\n#1 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\http\\src\\Filter\\FilterChain.php(110): Fusio\\Impl\\Filter\\Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#2 G:\\xampp\\htdocs\\fusio\\vendor\\fusio\\impl\\src\\Filter\\AssertMethod.php(95): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#3 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\http\\src\\Filter\\FilterChain.php(110): Fusio\\Impl\\Filter\\AssertMethod->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#4 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\http\\src\\Filter\\UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#5 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\http\\src\\Filter\\FilterChain.php(110): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#6 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Loader\\Loader.php(123): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#7 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Loader\\Loader.php(102): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#8 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Dispatch\\Dispatch.php(125): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Loader\\Context))\n#9 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Test\\ContainerTestCaseTrait.php(150): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#10 G:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Test\\ContainerTestCaseTrait.php(168): PSX\\Framework\\Test\\ControllerDbTestCase->loadController(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#11 G:\\xampp\\htdocs\\fusio\\tests\\Api\\Events\\CollectionTest.php(20): PSX\\Framework\\Test\\ControllerDbTestCase->sendRequest('\/events', 'GET', Array)\n#12 [internal function]: App\\Tests\\Api\\Events\\CollectionTest->testGet()\n#13 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\Framework\\TestCase.php(1071): ReflectionMethod->invokeArgs(Object(App\\Tests\\Api\\Events\\CollectionTest), Array)\n#14 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\Framework\\TestCase.php(939): PHPUnit\\Framework\\TestCase->runTest()\n#15 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\Framework\\TestResult.php(698): PHPUnit\\Framework\\TestCase->runBare()\n#16 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\Framework\\TestCase.php(894): PHPUnit\\Framework\\TestResult->run(Object(App\\Tests\\Api\\Events\\CollectionTest))\n#17 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\Framework\\TestSuite.php(755): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))\n#18 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\Framework\\TestSuite.php(755): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))\n#19 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\TextUI\\TestRunner.php(545): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))\n#20 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\TextUI\\Command.php(195): PHPUnit\\TextUI\\TestRunner->doRun(Object(PHPUnit\\Framework\\TestSuite), Array, true)\n#21 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\src\\TextUI\\Command.php(148): PHPUnit\\TextUI\\Command->run(Array, true)\n#22 G:\\xampp\\htdocs\\fusio\\vendor\\phpunit\\phpunit\\phpunit(53): PHPUnit\\TextUI\\Command::main()\n#23 {main}",
    "context": "104 \n105                 try {\n106                     $token = $this-&gt;getToken($accessToken, $context-&gt;getRouteId(), $requestMethod);\n107                 } catch (\\UnexpectedValueException $e) {\n<b>108                     throw new UnauthorizedException($e-&gt;getMessage(), 'Bearer', $params);\n<\/b>109                 }\n110 \n111                 if ($token instanceof Model\\Token) {\n112                     $app  = $this-&gt;appRepository-&gt;get($token-&gt;getAppId());\n"
}
Failed asserting that 401 matches expected 200.
```
When I compare to the Todo App test cases, it has 64 character accesstoken, but when I generate  access token using Oauth I am getting 272 character token, so i am confused . Please helpme to fix it.

**Comment by jothikannan** [comment]
I have fixed it myself, I tried the same access token used on Todo app, just changed the scope in Fixture.php and now everything is working fine.
