### ISSUE TITLE
deploy issue

### ISSUE THREAD

**Issue by dataforce-troy** [apioo/fusio#341]
When FUSIO_ENV is set to "prod" and I use "bin/fusio deploy" it seems like the autoloader is not loading some service classes as I receive the following error: 

```
An exception occurred during deploy. No changes are applied to the database.

Message: Service App\Service\Suburb not defined
Trace: #0 /var/www/html/asap-api.dataforce.com.au/vendor/psx/dependency/src/TypeResolver.php(75): PSX\Dependency\Container->get('App\\Service\\Sub...')
```

However, if I change FUSIO_ENV to "dev", then I can run the same deploy command (without any other changes) and it deploys the suburb route just fine. I am also having this same problem with 5 other routes in my app. Deploy will bomb out and throw an error saying the service is undefined if I try to deploy when FUSIO_ENV is set to "prod".

Once deployed (in dev mode), the route will work fine while still in "dev" mode, but in "prod" mode it will fail. For example if I call /suburbs/1 when FUSIO_ENV is "prod" I get this response:
```
{
  "success": false,
  "title": "Internal Server Error",
  "message": "The server encountered an internal error and was unable to complete your request."
}
```
However if I change it back to "dev" it works:

```
{
  "suburbId": 1,
  "name": "RUSHCUTTERS BAY",
  "postCode": 2011,
  "state": "NSW",
  "lgaId": 123,
  "lga": "Sydney",
  "enabled": true
}
```
If I output $exception->message() in Converter.php (line 87), it says "Service App\\Service\\Suburb not defined"

**Comment by ratsey** [comment]
I've reverted to doing my configs through the UI as I have some custom classes that just don't work with the deploy function - no errors, just nothing returned and no updates. Originally was going to use the deploy to keep my changes in Git, but now will just use DB backups to keep track of changes.

**Comment by chriskapp** [comment]
Hi, in general if you set the env to prod Fusio writes more data to the cache/ folder to improve performance. Please try to empty the cache folder and try the prod call again.

**Comment by dataforce-troy** [comment]
@chriskapp Thank you for your response. I have tried clearing cache but unfortunately this did not help.

Output below, showing a successfully deploy when in dev mode, then trying to deploy after clearing cache and changing to prod mode.
```

[user@localhost]$ php bin/fusio deploy
- [UPDATED] config Changed 21 values
- [UPDATED] connection ASAP
- [UPDATED] schema Message
- [UPDATED] schema ErrorResponse
- [UPDATED] schema Error
- [UPDATED] schema Search
- [UPDATED] schema Appointment
- [UPDATED] schema Appointment-Create
- [UPDATED] schema Appointment-Collection
- [UPDATED] schema Appointment-Answer-Collection
- [UPDATED] schema Appointment-Invoice
- [UPDATED] schema Job
- [UPDATED] schema Job-Create
- [UPDATED] schema Job-View
- [UPDATED] schema Job-Collection
- [UPDATED] schema Job-Quote
- [UPDATED] schema Customer
- [UPDATED] schema Customer-Create
- [UPDATED] schema Customer-Collection
- [UPDATED] schema Fieldworker
- [UPDATED] schema Fieldworker-Collection
- [UPDATED] schema Product
- [UPDATED] schema Product-Collection
- [UPDATED] schema Agent
- [UPDATED] schema Agent-Collection
- [UPDATED] schema Question
- [UPDATED] schema Question-Collection
- [UPDATED] schema QuestionAnswer
- [UPDATED] schema Question-Answer-Collection
- [UPDATED] schema Client
- [UPDATED] schema Client-Collection
- [UPDATED] schema File
- [UPDATED] schema File-Collection
- [UPDATED] schema FileCategory
- [UPDATED] schema FileCategory-Collection
- [UPDATED] schema WorkType
- [UPDATED] schema WorkType-Collection
- [UPDATED] schema Suburb
- [UPDATED] schema Suburb-Collection
- [UPDATED] schema FilterGroup
- [UPDATED] schema Filter
- [UPDATED] action App_Action_Appointment_Insert
- [UPDATED] action App_Action_Appointment_Search
- [UPDATED] action App_Action_Appointment_Row
- [UPDATED] action App_Action_File_CollectionByAppointment
- [UPDATED] action App_Action_Appointment_AnswerCollection
- [UPDATED] action App_Action_Appointment_Invoice_Row
- [UPDATED] action App_Action_Job_Insert
- [UPDATED] action App_Action_Job_Row
- [UPDATED] action App_Action_Appointment_Collection
- [UPDATED] action App_Action_File_CollectionByJob
- [UPDATED] action App_Action_Job_Quote_Row
- [UPDATED] action App_Action_Customer_Insert
- [UPDATED] action App_Action_Customer_Search
- [UPDATED] action App_Action_Customer_RowById
- [UPDATED] action App_Action_Job_CollectionByCustomerId
- [UPDATED] action App_Action_Customer_CollectionByRef
- [UPDATED] action App_Action_Job_CollectionByCustomerRef
- [UPDATED] action App_Action_Fieldworker_Collection
- [UPDATED] action App_Action_Fieldworker_Row
- [UPDATED] action App_Action_Product_Collection
- [UPDATED] action App_Action_Product_Row
- [UPDATED] action App_Action_Agent_Collection
- [UPDATED] action App_Action_Agent_Row
- [UPDATED] action App_Action_Question_Collection
- [UPDATED] action App_Action_Question_Row
- [UPDATED] action App_Action_QuestionAnswer_Collection
- [UPDATED] action App_Action_Client_Collection
- [UPDATED] action App_Action_Client_Row
- [UPDATED] action App_Action_File_Insert
- [UPDATED] action App_Action_FileCategory_Collection
- [UPDATED] action App_Action_File_Row
- [UPDATED] action App_Action_WorkType_Collection
- [UPDATED] action App_Action_WorkType_Row
- [UPDATED] action App_Action_Suburb_Collection
- [UPDATED] action App_Action_Suburb_Row
- [UPDATED] action App_Action_Welcome
- [UPDATED] routes /:instance/appointments
- [UPDATED] routes /:instance/appointments/search
- [UPDATED] routes /:instance/appointments/:appointment_id
- [UPDATED] routes /:instance/appointments/:appointment_id/files
- [UPDATED] routes /:instance/appointments/:appointment_id/answers
- [UPDATED] routes /:instance/appointments/:appointment_id/invoice
- [UPDATED] routes /:instance/jobs
- [UPDATED] routes /:instance/jobs/:job_id
- [UPDATED] routes /:instance/jobs/:job_id/appointments
- [UPDATED] routes /:instance/jobs/:job_id/files
- [UPDATED] routes /:instance/jobs/:job_id/quote
- [UPDATED] routes /:instance/customers
- [UPDATED] routes /:instance/customers/search
- [UPDATED] routes /:instance/customers/id/:customer_id
- [UPDATED] routes /:instance/customers/id/:customer_id/jobs
- [UPDATED] routes /:instance/customers/ref/:customer_ref
- [UPDATED] routes /:instance/customers/ref/:customer_ref/jobs
- [UPDATED] routes /:instance/fieldworkers
- [UPDATED] routes /:instance/fieldworkers/:fieldworker_id
- [UPDATED] routes /:instance/products
- [UPDATED] routes /:instance/products/:product_id
- [UPDATED] routes /:instance/agents
- [UPDATED] routes /:instance/agents/:agent_id
- [UPDATED] routes /:instance/questions
- [UPDATED] routes /:instance/questions/:question_id
- [UPDATED] routes /:instance/questions/:question_id/answers
- [UPDATED] routes /:instance/clients
- [UPDATED] routes /:instance/clients/:client_id
- [UPDATED] routes /:instance/files
- [UPDATED] routes /:instance/files/categories
- [UPDATED] routes /:instance/files/:file_id
- [UPDATED] routes /:instance/work-types
- [UPDATED] routes /:instance/work-types/:work_type_id
- [UPDATED] routes /:instance/suburbs
- [UPDATED] routes /:instance/suburbs/:suburb_id
- [UPDATED] routes /
- [UPDATED] event customer_created
- [UPDATED] event customer_updated
- [UPDATED] event job_created
- [UPDATED] event job_updated
- [UPDATED] event appointment_created
- [UPDATED] event appointment_updated

Deploy successful!

[user@localhost]$ php bin/fusio system:clear_cache
Cache cleared
[user@localhost]$ php bin/fusio system:clean
Clean up successful!
[user@localhost]$ vi .env
[user@localhost]$ php bin/fusio system:clear_cache
Cache cleared
[user@localhost]$ php bin/fusio system:clean
Clean up successful!
[user@localhost]$ php bin/fusio deploy            
An exception occurred during deploy. No changes are applied to the database.

Message: Service App\Service\AppointmentAnswer not defined
Trace: #0 /var/www/html/fusio-api/vendor/psx/dependency/src/TypeResolver.php(75): PSX\Dependency\Container->get('App\\Service\\App...')
#1 /var/www/html/fusio-api/vendor/psx/dependency/src/AutowireResolver.php(62): PSX\Dependency\TypeResolver->getServiceByType('App\\Service\\App...')
#2 /var/www/html/fusio-api/vendor/fusio/engine/src/Factory/Resolver/PhpClass.php(56): PSX\Dependency\AutowireResolver->getObject('App\\Action\\Appo...')
#3 /var/www/html/fusio-api/vendor/fusio/engine/src/Factory/Action.php(82): Fusio\Engine\Factory\Resolver\PhpClass->resolve('App\\Action\\Appo...')
#4 /var/www/html/fusio-api/vendor/fusio/engine/src/Parser/ParserAbstract.php(90): Fusio\Engine\Factory\Action->factory('App\\Action\\Appo...')
#5 /var/www/html/fusio-api/vendor/fusio/engine/src/Parser/ParserAbstract.php(63): Fusio\Engine\Parser\ParserAbstract->getObject('App\\Action\\Appo...')
#6 /var/www/html/fusio-api/vendor/fusio/impl/src/Service/System/SystemAbstract.php(149): Fusio\Engine\Parser\ParserAbstract->getForm('App\\Action\\Appo...')
#7 /var/www/html/fusio-api/vendor/fusio/impl/src/Service/System/SystemAbstract.php(120): Fusio\Impl\Service\System\SystemAbstract->transformAction(Object(stdClass))
#8 /var/www/html/fusio-api/vendor/fusio/impl/src/Service/System/Import.php(117): Fusio\Impl\Service\System\SystemAbstract->transform('action', Object(stdClass))
#9 /var/www/html/fusio-api/vendor/fusio/impl/src/Service/System/Import.php(94): Fusio\Impl\Service\System\Import->importGeneral('action', Object(stdClass), Object(Fusio\Impl\Service\System\Import\Result))
#10 /var/www/html/fusio-api/vendor/fusio/impl/src/Service/System/Deploy.php(118): Fusio\Impl\Service\System\Import->import(Object(stdClass))
#11 /var/www/html/fusio-api/vendor/fusio/impl/src/Console/System/DeployCommand.php(112): Fusio\Impl\Service\System\Deploy->deploy(Array, '/var/www/html/a...')
#12 /var/www/html/fusio-api/vendor/symfony/console/Command/Command.php(255): Fusio\Impl\Console\System\DeployCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/fusio-api/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/fusio-api/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(Fusio\Impl\Console\System\DeployCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/fusio-api/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/fusio-api/bin/fusio(47): Symfony\Component\Console\Application->run()
#17 {main}
[user@localhost]$ 
```

**Comment by dataforce-troy** [comment]
@chriskapp Any ideas? What does deploy do differently in 'prod' mode compared to 'dev' mode that could cause this?

**Comment by chriskapp** [comment]
Hi, mhh the exception comes from the DI TypeResolver, internally Fusio geenrates a compiled DI container in prod mode, so that we dont have to do the work of looking at the return types on a prod machine. In your case it looks like the cache does not contain the service `App\Service\AppointmentAnswer` which you have otherwise declared at the DI container? So I would guess that this DI cache is the problem, you may also take a look at the `cache/container.compiled.php` file and also delete this file which should be then regenerated.

**Comment by dataforce-troy** [comment]
@chriskapp Thanks mate, I had previously used 'bin/fusio system:clear_cache' to clear the cache but it looks like this command doesn't clear all files in cache direction (including container.compiled.php). 

I tried manually clearing out the cache directory by removing everything in there and was able to run a successfully deploy in prod mode.
