### ISSUE TITLE
"Unknown location in D:\\xampp\\htdocs\\fusio1\\vendor\\psx\\framework\\src\\Loader\\Loader.php on line 75",

### ISSUE THREAD

**Issue by getsettalk** [apioo/fusio#506]
Please Tell me how to solve this problem , i have installed it htdocs/fusio1 folder ,
When hit url : http://localhost/fusio1/public/

than its showing this json error :

```
{
"success": false,
"title": "PSX\\Framework\\Loader\\InvalidPathException",
"message": "Unknown location in D:\\xampp\\htdocs\\fusio1\\vendor\\psx\\framework\\src\\Loader\\Loader.php on line 75",
"trace": "#0 D:\\xampp\\htdocs\\fusio1\\vendor\\psx\\framework\\src\\Dispatch\\Dispatch.php(95): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Framework\\Loader\\Context))\n#1 D:\\xampp\\htdocs\\fusio1\\vendor\\psx\\engine\\src\\WebServer\\Engine.php(52): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#2 D:\\xampp\\htdocs\\fusio1\\vendor\\psx\\framework\\src\\Environment\\Environment.php(54): PSX\\Engine\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch))\n#3 D:\\xampp\\htdocs\\fusio1\\public\\index.php(28): PSX\\Framework\\Environment\\Environment->serve()\n#4 {main}",
"context": "71              $controller = $this-&gt;controllerFactory-&gt;getController($context-&gt;getSource(), $context);\n72  \n73              $this-&gt;execute($controller, $result, $response);\n74          } else {\n<b>75              throw new InvalidPathException(&#039;Unknown location&#039;, $request);\n</b>76          }\n77      }\n78  \n79      public function execute(array $controller, RequestInterface $request, ResponseInterface $response): void\n"
}
```

**Comment by chriskapp** [comment]
Hi @getsettalk, can you check whether the url is correctly configured at the `.env` file
