### ISSUE TITLE
Fusio unable to find action class

### ISSUE THREAD

**Issue by subangkit** [apioo/fusio#558]
I have operation like this 

```
scopes: ["user_data"]
stability: 1
public: true
description: "Return active user data"
httpMethod: GET
httpPath: "/whoami"
httpCode: 200
outgoing: "App\\Model\\UserData"
throws:
  500: "App\\Model\\Message"
action: "App\\Action\\UserData\\WhoAmI"
```

But action class App\\Action\\UserData\\WhoAmI can't recognized by the engine.
What's wrong with that?

I've been following instructions on YouTube and sample on https://github.com/apioo/fusio-sample-cms

**Comment by chriskapp** [comment]
Hi @subangkit in general this should work, you could check the following:
* Composer autoloading works s. https://github.com/apioo/fusio-sample-cms/blob/master/composer.json#L44 ... you could also run `composer dumpautoload`
* Check that your action is loaded by the DI config s. https://github.com/apioo/fusio-sample-cms/blob/master/resources/container.php#L11 and delete the container cache under `cache/`

**Comment by subangkit** [comment]
Yes, I've update autoload with option ```composer dump-autoload -o``` and class has been maaped in vendor/composer/autoload_classmap.php

If I tracing using that class in the index.php, I able to call class using ```$a = new App\Action\UserData\WhoAmI();``` but fusio couldn't resolved in the vendor/fusio/engine/src/Factory/Action.php line 49

``` if (!$this->actions->has($className)) {```

```
    public function factory(string $className): EngineActionInterface
    {
        $className = ClassName::unserialize($className);

        if (!$this->actions->has($className)) {
            throw new ActionNotFoundException('Action class ' . $className . ' not found');
        }

        $action = $this->actions->get($className);
        if (!$action instanceof EngineActionInterface) {
            throw new ActionNotFoundException('Action class ' . $className . ' is available but it must implement the interface: ' . EngineConnectionInterface::class);
        }

        return $action;
    }
```

Output from endpoint

```json
{
    "success": false,
    "title": "Fusio\\Engine\\Exception\\ActionNotFoundException",
    "message": "Action class App\\Action\\UserData\\WhoAmI not found in /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/engine/src/Factory/Action.php on line 50",
    "trace": "#0 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/engine/src/Processor.php(67): Fusio\\Engine\\Factory\\Action->factory('App\\\\Action\\\\User...')\n#1 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/impl/src/Service/Action/Invoker.php(76): Fusio\\Engine\\Processor->execute('php+class://App...', Object(Fusio\\Engine\\Request), Object(Fusio\\Engine\\Context))\n#2 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/impl/src/Controller/ActionController.php(59): Fusio\\Impl\\Service\\Action\\Invoker->invoke(Object(Fusio\\Engine\\Request), Object(Fusio\\Engine\\Context))\n#3 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/impl/src/Framework/Filter/ActionExecutor.php(77): Fusio\\Impl\\Controller\\ActionController->execute(Object(Fusio\\Engine\\Request), Object(Fusio\\Impl\\Framework\\Loader\\Context))\n#4 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/FilterChain.php(86): Fusio\\Impl\\Framework\\Filter\\ActionExecutor->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#5 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/impl/src/Controller/Filter/Logger.php(60): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#6 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/FilterChain.php(86): Fusio\\Impl\\Controller\\Filter\\Logger->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#7 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/impl/src/Controller/Filter/RequestLimit.php(63): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#8 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/FilterChain.php(86): Fusio\\Impl\\Controller\\Filter\\RequestLimit->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#9 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/impl/src/Controller/Filter/Authentication.php(57): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#10 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/FilterChain.php(86): Fusio\\Impl\\Controller\\Filter\\Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#11 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/fusio/impl/src/Controller/Filter/AssertOperation.php(87): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#12 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/FilterChain.php(86): Fusio\\Impl\\Controller\\Filter\\AssertOperation->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#13 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#14 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/FilterChain.php(86): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#15 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/CORS.php(86): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#16 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/http/src/Filter/FilterChain.php(86): PSX\\Http\\Filter\\CORS->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#17 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/framework/src/Loader/Loader.php(97): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#18 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/framework/src/Loader/Loader.php(72): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Framework\\Loader\\Context))\n#19 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/framework/src/Dispatch/Dispatch.php(86): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Framework\\Loader\\Context))\n#20 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/engine/src/WebServer/Engine.php(51): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#21 /home/micq1438/public_html/api.micrologis.id/fusio/vendor/psx/framework/src/Environment/Environment.php(49): PSX\\Engine\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch))\n#22 /home/micq1438/public_html/api.micrologis.id/fusio/public/index.php(36): PSX\\Framework\\Environment\\Environment->serve()\n#23 {main}",
    "context": "46      {\n47          $className = ClassName::unserialize($className);\n48  \n49          if (!$this-&gt;actions-&gt;has($className)) {\n<b>50              throw new ActionNotFoundException(&#039;Action class &#039; . $className . &#039; not found&#039;);\n</b>51          }\n52  \n53          $action = $this-&gt;actions-&gt;get($className);\n54          if (!$action instanceof EngineActionInterface) {\n"
}
```

I has setting the configuration.php file 
```    'fusio_engine' => \Fusio\Engine\Action\Resolver\PhpClass::class,```
But still forcing same issue

**Comment by chriskapp** [comment]
It looks like your class was not added to the internal DI, could you check the file `cache/container.php` and check whether it contains your class. Also make sure that you class has the fitting namespace, in your case it must be `App\Action\UserData`. Otherwise could you provide me a minimal setup as zip so that I can locally reproduce the error?

**Comment by subangkit** [comment]
Yes, you are right, container.php needs to be updated the same as the local environment. Now deployment is running smoothly after adding auto-synchronization files between local and production.

**Comment by subangkit** [comment]
Yes, you are right, container.php needs to be updated the same as the local environment. Now deployment is running smoothly after adding auto-synchronization files between local and production.
