### ISSUE TITLE
PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/opt/lappstack-7.1.9-0/apps/fusio/cache/psx" is not writable.

### ISSUE THREAD

**Issue by dragon28** [apioo/fusio#77]
Hello People,

I try to access the "http://localhost/fusio/public" webpage, however it turn out that the webpage become blank or unaccessible.

Therefore I went to check the apache log and find: 

```
[Tue Oct 17 17:59:38.097530 2017] [[php7:error] [pid 4282] [client 127.0.0.1:60916] PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/opt/lappstack-7.1.9-0/apps/fusio/cache/psx" is not writable. in /opt/lappstack-7.1.9-0/apps/fusio/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92\nStack trace:\n#0 /opt/lappstack-7.1.9-0/apps/fusio/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FilesystemCache.php(37): Doctrine\\Common\\Cache\\FileCache->__construct('/opt/lappstack-...', '.doctrinecache....', 2)\n#1 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/DefaultContainer.php(255): Doctrine\\Common\\Cache\\FilesystemCache->__construct('/opt/lappstack-...')\n#2 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/DefaultContainer.php(81): PSX\\Framework\\Dependency\\DefaultContainer->newDoctrineCacheImpl('psx')\n#3 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/Container.php(88): PSX\\Framework\\Dependency\\DefaultContainer->getCache()\n#4 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/Framework.php(74): PSX\\Framework\\ in /opt/lappstack-7.1.9-0/apps/fusio/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php on line 92
[Tue Oct 17 17:59:44.941172 2017] [php7:error] [pid 4282] [client 127.0.0.1:60916] PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/opt/lappstack-7.1.9-0/apps/fusio/cache/psx" is not writable. in /opt/lappstack-7.1.9-0/apps/fusio/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92\nStack trace:\n#0 /opt/lappstack-7.1.9-0/apps/fusio/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FilesystemCache.php(37): Doctrine\\Common\\Cache\\FileCache->__construct('/opt/lappstack-...', '.doctrinecache....', 2)\n#1 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/DefaultContainer.php(255): Doctrine\\Common\\Cache\\FilesystemCache->__construct('/opt/lappstack-...')\n#2 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/DefaultContainer.php(81): PSX\\Framework\\Dependency\\DefaultContainer->newDoctrineCacheImpl('psx')\n#3 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/Container.php(88): PSX\\Framework\\Dependency\\DefaultContainer->getCache()\n#4 /opt/lappstack-7.1.9-0/apps/fusio/vendor/psx/framework/src/Dependency/Framework.php(74): PSX\\Framework\\ in /opt/lappstack-7.1.9-0/apps/fusio/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php on line 92
```
PHP 7.1.9
Apache/2.4.27 
mysql version: 15.1 Distrib 10.1.26-MariaDB, for Linux (x86_64) using readline 5.1

Thanks

**Comment by k42b3** [comment]
Hi, this simply means that Fusio is not able to write to the `cache/` folder. You need to set the permissions accordingly. The user of your webserver should be the owner of the `cache/` directory i.e. with `chown -r www-data: cache/`. This should fix the problem, in case the owner has no write permissions you must set them with i.e. `chmod 744 cache/`

**Comment by dragon28** [comment]
hello @k42b3 

Thank you for reply :+1: 

Yup, you were correct.

I change the permission to 775 using "sudo chmod 775 -R cache/" and fixed it.

Thanks
