### ISSUE TITLE
How to build response that contains array?

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#81]
I tried to have a JSON response that looks like this

```json
[
  {
    "id": 1,
    "name": "foo"
  },
  {
    "id": 2,
    "name": "bar"
  }
]
```

but I get 

```
{
	"success": false,
	"title": "InvalidArgumentException",
	"message": "Data must be an object in \/fusio\/installation\/directory\/vendor\/psx\/data\/src\/Exporter\/Popo.php on line 54",
	"trace": "#0 \/fusio\/installation\/directory\/vendor\/psx\/data\/src\/Processor.php(166): PSX\\Data\\Exporter\\Popo->export(Array)\n#1 \/fusio\/installation\/directory\/vendor\/psx\/data\/src\/Processor.php(152): PSX\\Data\\Processor->transform(Array)\n#2 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Controller\/ControllerAbstract.php(343): PSX\\Data\\Processor->write(Object(PSX\\Data\\Payload))\n#3 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Controller\/ControllerAbstract.php(270): PSX\\Framework\\Controller\\ControllerAbstract->setResponse(Array, NULL)\n#4 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Controller\/SchemaApiAbstract.php(332): PSX\\Framework\\Controller\\ControllerAbstract->setBody(Array)\n#5 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Controller\/SchemaApiAbstract.php(121): PSX\\Framework\\Controller\\SchemaApiAbstract->sendResponse(Object(PSX\\Api\\Resource\\Get), Array)\n#6 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Filter\/ControllerExecutor.php(52): PSX\\Framework\\Controller\\SchemaApiAbstract->onGet()\n#7 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Filter\/FilterChain.php(79): PSX\\Framework\\Filter\\ControllerExecutor->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Filter\\FilterChain))\n#8 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Filter\/Oauth2Authentication.php(86): PSX\\Framework\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#9 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Filter\/FilterChain.php(79): PSX\\Framework\\Filter\\Oauth2Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Filter\\FilterChain))\n#10 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Filter\/UserAgentEnforcer.php(41): PSX\\Framework\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#11 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Filter\/FilterChain.php(79): PSX\\Framework\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Filter\\FilterChain))\n#12 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Loader\/Loader.php(158): PSX\\Framework\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#13 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Loader\/Loader.php(126): PSX\\Framework\\Loader\\Loader->executeController(Object(Fusio\\Impl\\Controller\\SchemaApiController), Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#14 \/fusio\/installation\/directory\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(131): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#15 \/fusio\/installation\/directory\/public\/index.php(30): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#16 {main}",
	"context": "50              return $data;\n51          } elseif (is_object($data)) {\n52              return $this-&gt;dumper-&gt;dump($data);\n53          } else {\n<b>54              throw new \\InvalidArgumentException('Data must be an object');\n<\/b>55          }\n56      }\n57  }\n"
}
```

How to solve it?

**Comment by k42b3** [comment]
at the moment this is a restriction of Fusio. So it is only possible to generate "object" responses. I.e. in your case you would need to wrap the array in an object:

```
{
  "items": [
    {
      "id": 1,
      "name": "foo"
    },
    {
      "id": 2,
      "name": "bar"
    }
  ]
}
```

this comes from our underling framework which has also the possibility to transform the JSON response into XML and because of this there is a need that the top data structure is always an object. So we have no simple way to allow such array structures. But I would like to investigate this topic later on whether this is somehow possible.

**Comment by k42b3** [comment]
With the latest release it is now possible to use also simple array responses.
