### ISSUE TITLE
127.0.0.1 show error

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#87]
i went to 127.0.0.1 and it show me this

> {
>     "success": false,
>     "title": "Doctrine\\DBAL\\Exception\\DriverException",
>     "message": "An exception occured in driver: could not find driver in \/var\/www\/fusio\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php on line 115",
>     "trace": "#0 \/var\/www\/fusio\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(145): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/fusio\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOMySql\/Driver.php(47): Doctrine\\DBAL\\DBALException::driverException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException))\n#2 \/var\/www\/fusio\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect(Array, 'root', '123', Array)\n#3 \/var\/www\/fusio\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(833): Doctrine\\DBAL\\Connection->connect()\n#4 \/var\/www\/fusio\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(785): Doctrine\\DBAL\\Connection->executeQuery('SELECT id,\\n    ...', Array, Array)\n#5 \/var\/www\/fusio\/vendor\/fusio\/impl\/src\/Loader\/RoutingParser.php(85): Doctrine\\DBAL\\Connection->fetchAll('SELECT id,\\n    ...', Array)\n#6 \/var\/www\/fusio\/vendor\/psx\/framework\/src\/Loader\/Loader.php(117): Fusio\\Impl\\Loader\\RoutingParser->resolve(Object(PSX\\Http\\Request), Object(PSX\\Framework\\Loader\\Context))\n#7 \/var\/www\/fusio\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(131): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#8 \/var\/www\/fusio\/public\/index.php(30): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#9 {main}",
>     "context": "111             case '1566':\n112                 return new Exception\\NotNullConstraintViolationException($message, $exception);\n113         }\n114 \n<b>115         return new Exception\\DriverException($message, $exception);\n<\/b>116     }\n117 \n118     \/**\n119      * {@inheritdoc}\n"
> }

**Comment by koswarabilly** [comment]
just reinstall everything it will work
